---
defaultAirflowRepository: "docker.io/apache/airflow"
defaultAirflowTag: "2.4.1-python3.10"
airflowVersion: "2.4.1"

executor: "KubernetesExecutor"

# The Flask secret key for Airflow Webserver to encrypt browser session.
# python3 -c 'import secrets; print(secrets.token_hex(16))'
webserverSecretKey: eea66b80fd055e0a30e2ca2e6c278ddc

dags:
  persistence:
    enabled: true
    existingClaim: airflow-dags
  gitSync:
    enabled: false

ingress:
  web:
    enabled: true
    hosts:
      - "airflow.k3s-demo"

logs:
  persistence:
    enabled: true
    existingClaim: airflow-logs

extraEnv: |
  - name: AIRFLOW__CORE__LOAD_EXAMPLES
    value: "True"
